baseURL = 'https://icarus-go.github.io'
languageCode = 'zh-CN'
title = 'Mr.Quinson Blog'
theme = 'paper'
publishDir = "docs"
isqusShortname = 'Quinson'   # use disqus comments
paginate = 3

[params]
# color style
color = 'linen'                           # linen, wheat, gray, light

# header social icons
github = 'icarus-go'                 # github.com/YOUR_GITHUB_ID

# home page profile
avatar = 'https://s1.ax1x.com/2023/03/06/ppV3SbT.jpg'                 # gravatar email or image url
name = 'Quinson'
bio = '再给我两份葱,让我把鲫鱼煎成饼. (有问题可以通过邮箱和我联系)'


# misc
disableHLJS = true                        # disable highlight.js
monoDarkIcon = true                       # show monochrome dark mode icon
gravatarCdn = ''         # e.g. 'https://cdn.v2ex.com/gravatar/'
graphCommentId = ""  # use graph comment (disqus alternative)

[menu]

[[menu.main]]
identifier = "Mac OS X"
name = "Mac OS X"
url = "/tags/macos"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Menu"
url = "/tags/"
weight = 10
