baseURL = 'https://icarus-go.github.io'
languageCode = 'zh-CN'
title = 'Mr.Quinson Blog'
theme = 'paper'
publishDir = "docs"
isqusShortname = 'Quinson'   # use disqus comments


[params]
# color style
color = 'linen'                           # linen, wheat, gray, light

# header social icons
twitter = 'YOUR_TWI
TTER_ID'               # twitter.com/YOUR_TWITTER_ID
github = 'icarus-go'                 # github.com/YOUR_GITHUB_ID
instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
rss = true                                # show rss icon

# home page profile
avatar = 'https://s1.ax1x.com/2023/03/06/ppV3SbT.jpg'                 # gravatar email or image url
name = 'Quinson'
bio = '简简单单的 Go 开发者'


# misc
disableHLJS = false                        # disable highlight.js
monoDarkIcon = true                       # show monochrome dark mode icon
gravatarCdn = ''         # e.g. 'https://cdn.v2ex.com/gravatar/'
graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)